INSERT INTO PROJECT(TITLE) VALUES('he');
INSERT INTO PROJECT(TITLE) VALUES('ho');

INSERT INTO BLOCK(PROJECT_ID, TITLE, COMPONENT) VALUES(1, 'Hello', 'identity');
INSERT INTO BLOCK(PROJECT_ID, TITLE, COMPONENT) VALUES(1, 'World', 'identity');
INSERT INTO BLOCK(PROJECT_ID, TITLE, COMPONENT) VALUES(1, 'Pop', 'identity');
INSERT INTO BLOCK(PROJECT_ID, TITLE, COMPONENT) VALUES(1, 'Lop', 'identity');
INSERT INTO BLOCK(PROJECT_ID, TITLE, COMPONENT) VALUES(2, 'Hello', 'identity');
INSERT INTO BLOCK(PROJECT_ID, TITLE, COMPONENT) VALUES(2, 'World', 'identity');

INSERT INTO WIRE(INPUT_ID, OUTPUT_ID) VALUES(1, 2);
INSERT INTO WIRE(INPUT_ID, OUTPUT_ID) VALUES(1, 3);
